name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login testdockerbhavz.azurecr.io -u testdockerbhavz --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t testdockerbhavz.azurecr.io/studentperformance:latest .
          docker push testdockerbhavz.azurecr.io/studentperformance:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: studentperformancecheck1
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: testdockerbhavz.azurecr.io/studentperformance:latest
